services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    environment:
      - IS_LOCAL=false
      - IS_AWS=${IS_AWS:-false}
      - MOCK_MODE=${MOCK_MODE:-false}
      - DIARIZATION=${DIARIZATION:-false}
      - VECTOR_STORE_DIR=/app/data/vector_stores
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - ./backend/temp:/app/temp
    ports:
      - "8001:8001"
    restart: unless-stopped
    depends_on:
      - ollama

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8001

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  ollama_data: